Concurrency 3.1 - Add virtual and qualifier elements to resource definitions
jakartaee/jakartaee-schemas pull request #44
Opened 2023-12-05 23:28 UTC by KyleAure

Fixes #43

2023-12-06 00:35 UTC, starksm64 requested changes

2023-12-06 00:35 UTC, starksm64 commented on xml/test/application-concurrency.xml
> +    <qualifier>ee.jakarta.MyQualifier2</qualifier>
The ordering of the elements in the application_11.xsd for the managed-executorType has the virtual element before the qualifier element, which is why you are seeing validation errors.

2023-12-06 14:27 UTC, KyleAure commented
@starksm64 thanks for catching that!  I updated the test to have elements in the correct order.

I also updated the web-app-concurrency test which required me to copy/rename the web-app related schemas.

I also want to update the ejb-jar-concurrency test, which would mean we'd have to update the ejb-jar schema to change the following to EE 11: 
https://github.com/jakartaee/jakartaee-schemas/blob/efde9133c2f84ba0ce31fdf775278657a1da4742/xml/src/ejb-jar_4_0.xsds#L74

However there are no new versions of EJB for EE 10/11, so how can embedded resources within this schema be included?
As it stands right now the ejb-jar-concurrency test is failing with 125 errors because it includes elements from EE 10 that the schema doesn't include.

2023-12-06 18:22 UTC, starksm64 commented
> I also want to update the ejb-jar-concurrency test, which would mean we'd have to update the ejb-jar schema to change the following to EE 11:
> 
> https://github.com/jakartaee/jakartaee-schemas/blob/efde9133c2f84ba0ce31fdf775278657a1da4742/xml/src/ejb-jar_4_0.xsds#L74
> 
> However there are no new versions of EJB for EE 10/11, so how can embedded resources within this schema be included? As it stands right now the ejb-jar-concurrency test is failing with 125 errors because it includes elements from EE 10 that the schema doesn't include.
> 
> Reading some more issues it seems the determination is that EJB schema is frozen at EE 9. Therefore I removed the ejb-jar-concurrency test because it is invalid.
> 
> FYI @tbitonti - This may be of interest to you based on your issue #32

So we won't be able to update the ejb-jar-concurrency.xml test since we don't have any updated schema and there will be no requirements for EJB containers to support the new environments.

2023-12-12 14:54 UTC, njr-11 commented
We should consider positioning the new `qualifier` element right after `name`.  It might make sense to have this be more prominent in the configuration because it covers how applications reference/access these resources.

2023-12-13 14:22 UTC, njr-11 approved these changes

2024-01-03 17:16 UTC, starksm64 approved these changes

2024-01-03 17:16 UTC, merged

2024-06-06 19:15 UTC, edbratt commented
[How to Publish XML Schemas](https://jakartaee.github.io/platform/publish-xml-schemas) -- Sorry for the wrong link. It seems to incorrect in several places. I'll update the templates  (and a few other places where I noticed this).